FROM gradle:4.7.0-jdk8-alpine 
COPY --chown=gradle:gradle  . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon
EXPOSE 8080
RUN mkdir /home/gradle/app
RUN cp /home/gradle/src/build/libs/*.jar /home/gradle/app/spring-boot-application.jar
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/home/gradle/app/spring-boot-application.jar"]

